version: '3.8'
services:
  grouploss:
    build: .
    command: python train_resnet.py
    volumes:
      - .:/workspace
    ports:
      - "6006:6006"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
